[package]
name = "yaml-spanned"
version = "0.0.1"
edition = "2024"
authors = ["romnn <contact@romnn.com>"]
description = "YAML parser that captures detailed span information."
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/romnn/yaml-spanned"
repository = "https://github.com/romnn/yaml-spanned"
categories = ["encoding", "parser-implementations"]
keywords = [
	"yaml",
	"serde",
	"parser",
	"deserialization",
	"spans",
]
exclude = [
	".typos.toml",
	".ignore",
	".bumpversion.toml",
	"taskfile.yaml",
]

[features]
default = ["serde"]
serde = ["dep:serde"]

[package.metadata.cargo-feature-combinations]
denylist = ["default"]

[dependencies]
thiserror = "2"

# parsing
indexmap = "2"
itoa = "1"
ryu = "1"
libyaml-safer = "0"

# error reporting
codespan-reporting = "0"

# find duplicates
itertools = "0"

# optional
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
color-eyre = "0"
similar-asserts = "1"
serde_yaml = "0"
indoc = "2"
